// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCZVSbkK4Rvtnaw4YKdshwiLlBf_MCSds',
    appId: '1:736305070285:web:17680899113f40d38a6984',
    messagingSenderId: '736305070285',
    projectId: 'colaboraplus-bd22c',
    authDomain: 'colaboraplus-bd22c.firebaseapp.com',
    storageBucket: 'colaboraplus-bd22c.firebasestorage.app',
    measurementId: 'G-L6047HNRE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClWfKatvO1TmfSDK7LSdWu0obklYZKueE',
    appId: '1:736305070285:android:b6feee7ba46b207d8a6984',
    messagingSenderId: '736305070285',
    projectId: 'colaboraplus-bd22c',
    storageBucket: 'colaboraplus-bd22c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYPZdqZ_8_C3CfkzbIzXW-DPgQhR0mG_s',
    appId: '1:736305070285:ios:f7a88dff498e75d88a6984',
    messagingSenderId: '736305070285',
    projectId: 'colaboraplus-bd22c',
    storageBucket: 'colaboraplus-bd22c.firebasestorage.app',
    iosBundleId: 'com.example.matchhouseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYPZdqZ_8_C3CfkzbIzXW-DPgQhR0mG_s',
    appId: '1:736305070285:ios:f7a88dff498e75d88a6984',
    messagingSenderId: '736305070285',
    projectId: 'colaboraplus-bd22c',
    storageBucket: 'colaboraplus-bd22c.firebasestorage.app',
    iosBundleId: 'com.example.matchhouseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCZVSbkK4Rvtnaw4YKdshwiLlBf_MCSds',
    appId: '1:736305070285:web:26b38c51a5993d368a6984',
    messagingSenderId: '736305070285',
    projectId: 'colaboraplus-bd22c',
    authDomain: 'colaboraplus-bd22c.firebaseapp.com',
    storageBucket: 'colaboraplus-bd22c.firebasestorage.app',
    measurementId: 'G-XZGBC5HT3Q',
  );

}